### PR TITLE
Add files to build a deb src package for ppa upload

### PR DESCRIPTION
**Pull request by jcvernaleo**
This commit adds the files needed to generate a debina source package
suitable for uploading on launchpad to make a PPA (personal package
archive) for Ubuntu.

Due to the way Electron apps are genearlly packaged this is NOT
currently suitable for submission to the actual Debain archives
although it is fine for Launchpad (and I am still exploring ways to
improve it).

An corrected license file will be needed when that is decided upon.

User install instructions need to be added to the main README.md once
the final ppa path is decided on.

### CODE REVIEW

**Comment by gabmontes** [comment]
@jcvernaleo thanks for this. @eafelix will take a look at it.

Just to fully understand what are the requirements for Launchpad, what is wrong or missing with the current Debian installer we are building? @eafelix could explain the current build process.

https://github.com/MetronomeToken/metronome-desktop-wallet/releases/download/v0.6.0/metronome-desktop-wallet_v0.6.0.deb

**Comment by jcvernaleo** [comment]
@gabmontes The issue is that Launchpad doesn't let you upload a .deb file.  You have to upload a debian source package (.source, tarball, and I think one other file that I'm not remembering off hand).  That lets their system assemble the actual tarball.  It also lets it manage dependencies properly.  Strictly, it should also build the ode if possible but with electron that gets complicated since you can't just download random files in the chrooted debian/ubuntu build system so until I package some other things this depends on some pre-built files.  But it is good enough for launchpad (other electron based app have done it this way in the past as well, including atom at one point).

It would be great if elecctron-builder supported directly making debian source packages but it does not and they are not interested in adding it (there is a github issue I could dig up but it really is not an interesting discussion sadly).

So for now, I think the best way to do it is for you to leave your build stuff as is and then my ppa stuff can just build off that.  If I come up with a better method we might be able to unify the deb and debian source production but that isn't going to be the case at the moment.

Hope that clears it up a bit.

**Comment by gabmontes** [comment]
@jcvernaleo thanks! Very enlightening. Let's wait for @eafelix feedback and move on.

**Review by eafelix — APPROVED** [review]
Amazing! 👍

**Pull request merged**
