### PR TITLE
Fix converter estimates

### LINKED ISSUE #159: Converter estimate calls are the other way around
The amount returned as estimate for the conversion have to be swapped out. Should check if this is an issue with the events sent by the renderer or the logic in the main process.

### PR DESCRIPTION
**Pull request by pablen**
Closes #159

### CODE REVIEW

**Comment by gabmontes** [comment]
@pablen can you also update the main process code and check the issue is solved? I can do that too and add it to this PR. Let me know.

**Comment by pablen** [comment]
@gabmontes it is updated indeed. Also, tested and the issue is solved, of course ;)

**Comment by gabmontes** [comment]
@pablen you rock!

**Review by gabmontes — APPROVED** [review]

**Review by ianaya89 — APPROVED** [review]
LGTM

**Pull request merged**
